<?php
/*
    This file is part of the Contractika contract management software.
    Author: Yesbabylon SRL, 2022-2023
    License: GNU AGPL 3 license <http://www.gnu.org/licenses/>
*/
use equal\orm\Domain;


[$params, $providers] = eQual::announce([
    'description'   => 'Advanced search for SA lines: returns a collection of lines matching extra paramaters.',
    'extends'       => 'core_model_collect',
    'params'        => [
        'entity' =>  [
            'description'       => 'Full name (including namespace) of the class to look into (e.g. \'core\\User\').',
            'type'              => 'string',
            'default'           => 'contractika\SALine'
        ],
        'id' => [
            'type'              => 'integer',
            'description'       => "Identifier of the SA Line to fetch."
        ],
        'date_from' => [
            'type'              => 'date',
            'description'       => "First date of the time interval."
        ],
        'date_to' => [
            'type'              => 'date',
            'description'       => "Last date of the time interval."
        ],
        'customer_id' => [
            'type'              => 'many2one',
            'foreign_object'    => 'contractika\sale\customer\Customer',
            'description'       => 'Customer the line relates to (depending on service account).'
        ],
        'customer_identifier' => [
            'type'              => 'integer',
            'description'       => 'Numeric value of the ID of the Customer on which to filter the lines.'
        ],
        'employee_id' => [
            'type'              => 'many2one',
            'foreign_object'    => 'contractika\hr\employee\Employee',
            'description'       => 'The employee the time entry originates from.'
        ],
        'timeEntryID' => [
            'type'              => 'integer',
            'description'       => 'Time entry ID (int) generated by AutoTask PSA software.'
        ],
        'ticketNumber' => [
            'type'              => 'string',
            'description'       => 'Ticket number (string) generated by AutoTask PSA software.'
        ],
        'taskNumber' => [
            'type'              => 'string',
            'description'       => 'Task number (string) generated by AutoTask PSA software.',
        ],
        'is_locked' => [
            'type'              => 'string',
            'selection'         => [
                'all',
                'no',
                'yes'
            ],
            'description'       => '"Locked" - Flag marking the line as invoiced (has_report + report in `released` status).',
            'default'           => 'all'
        ],
        'is_posted' => [
            'type'              => 'string',
            'selection'         => [
                'all',
                'no',
                'yes'
            ],
            'description'       => '"Posted" - Flag marking the line as posted (approved in AT).',
            'default'           => 'all'
        ]
    ],
    'response'      => [
        'content-type'  => 'application/json',
        'charset'       => 'utf-8',
        'accept-origin' => '*'
    ],
    'providers'     => [ 'context', 'orm' ]
]);

/**
 * @var \equal\php\Context $context
 * @var \equal\orm\ObjectManager $orm
 */
list($context, $orm) = [ $providers['context'], $providers['orm'] ];


/*
    Add conditions to the domain to consider advanced parameters
*/

$domain = $params['domain'];

if(isset($params['id']) && $params['id'] > 0) {
    $domain = Domain::conditionAdd($domain, ['id', '=', $params['id']]);
}
if(isset($params['date_from']) && $params['date_from'] > 0) {
    $domain = Domain::conditionAdd($domain, ['date', '>=', date('c', $params['date_from'])]);
}
if(isset($params['date_to']) && $params['date_to'] > 0) {
    $domain = Domain::conditionAdd($domain, ['date', '<=', date('c', $params['date_to'])]);
}
if(isset($params['customer_id']) && $params['customer_id'] > 0) {
    $domain = Domain::conditionAdd($domain, ['customer_id', '=', $params['customer_id']]);
}
if(isset($params['customer_identifier']) && $params['customer_identifier'] > 0) {
    $domain = Domain::conditionAdd($domain, ['customer_id', '=', $params['customer_identifier']]);
}
if(isset($params['employee_id']) && $params['employee_id'] > 0) {
    $domain = Domain::conditionAdd($domain, ['employee_id', '=', $params['employee_id']]);
}
if(isset($params['timeEntryID']) && $params['timeEntryID'] > 0) {
    $domain = Domain::conditionAdd($domain, ['timeEntryID', '=', $params['timeEntryID']]);
}
if(isset($params['ticketNumber']) && strlen($params['ticketNumber'])) {
    $domain = Domain::conditionAdd($domain, ['has_ticket', '=', true]);
    $domain = Domain::conditionAdd($domain, ['ticketNumber', 'like', '%'.$params['ticketNumber'].'%']);
}
if(isset($params['taskNumber']) && strlen($params['taskNumber'])) {
    $domain = Domain::conditionAdd($domain, ['has_task', '=', true]);
    $domain = Domain::conditionAdd($domain, ['taskNumber', 'like', '%'.$params['taskNumber'].'%']);
}
if(isset($params['is_locked']) && in_array($params['is_locked'], ['no', 'yes'])) {
    $domain = Domain::conditionAdd($domain, ['is_locked', '=', ($params['is_locked'] === 'yes')]);
}
if(isset($params['is_posted']) && in_array($params['is_posted'], ['no', 'yes'])) {
    $domain = Domain::conditionAdd($domain, ['is_posted', '=', ($params['is_posted'] === 'yes')]);
}

$params['domain'] = $domain;

$result = eQual::run('get', 'model_collect', $params, true);

$context->httpResponse()
        ->body($result)
        ->send();
